# Generated by Django 4.2.30 on 2026-06-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('qa', 'Quality Assurance'), ('support', 'Support'), ('operations', 'Operations')], max_length=100),
        ),
    ]
